version: 2
updates:
  # ğŸ¤– æ›´æ–° GitHub Actions ç‰ˆæœ¬
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly" # æŒ‡å®šæ›´æ–°é¢‘ç‡
      time: "10:00" # æŒ‡å®šæ›´æ–°æ—¶é—´
      timezone: "Asia/Shanghai" # æŒ‡å®šæ—¶åŒº
    open-pull-requests-limit: 10 # é™åˆ¶åŒæ—¶æ‰“å¼€çš„PRæ•°é‡
    labels: # ä¸ºDependabotåˆ›å»ºçš„PRæ·»åŠ æ ‡ç­¾
      - "dependencies" # æ·»åŠ ä¸€ä¸ªåä¸º"dependencies"çš„æ ‡ç­¾
      - "automerge" # æ·»åŠ ä¸€ä¸ªåä¸º"automerge"çš„æ ‡ç­¾ï¼Œéœ€è¦é…åˆå·¥ä½œæµ
    # ignore:                       # å¿½ç•¥çš„ä¾èµ–
    # allow:                       # å…è®¸çš„ä¾èµ–
    groups:
      actions:
        patterns:
          - "*"
